
module master #(
    parameter ADDR_WIDTH = 32, 
    parameter DATA_WIDTH = 32
)(    
    // Global signals
    input  wire HCLK,
    input  wire HRESETn,

    // Master signals generated by this master
    output reg  [ADDR_WIDTH-1:0] HADDR,
    output reg  [2:0] HBURST,
    output reg  HMASTLOCK,
    output reg  [3:0] HPROT,
    output reg  [2:0] HSIZE,
    output reg  [1:0] HTRANS,
    output reg  [DATA_WIDTH-1:0] HWDATA,
    output reg  HWRITE,

    // Slave signals generated by a slave
    input  wire [DATA_WIDTH-1:0] HRDATA,
    input  wire HREADYOUT, 
    input  wire HRESP,

    // Processor Command signals 
    input  wire PVALID,
    input  wire PWRITE,
    input  wire [ADDR_WIDTH-1:0] PADDR,
    input  wire [DATA_WIDTH-1:0] PDATA,
    input  wire WRAP_INCR, // 1 = WRAP burst, 0 = INCR burst
    input  wire [7:0] BRUST_LEN, 
    input  wire [2:0] PSIZE,
    output reg  PREADY,
    
    // Response signals back to Processor
    output reg RES_VALID,
    output reg  [DATA_WIDTH-1:0] RES_DATA,
    output reg RES_ERROR
);

    // Transfer types 
    localparam IDLE = 2'b00;
    localparam BUSY = 2'b01;
    localparam NONSEQ = 2'b10;
    localparam SEQ = 2'b11;

    // FSM states 
    localparam S_IDLE = 3'd0;
    localparam S_ADDR = 3'd1;
    localparam S_DATA = 3'd2;

    // Internal Registers 
    reg [2:0] cs, ns;
    reg [7:0] BEAT_COUNT;
    reg [ADDR_WIDTH-1:0] REG_ADDR;
    reg [DATA_WIDTH-1:0] REG_DATA;
    reg REG_WRITE;
    reg [2:0] REG_SIZE;
    reg [ADDR_WIDTH-1:0] WRAP_MASK;

    // Combinational Address Calculation
    wire [ADDR_WIDTH-1:0] next_addr;
    assign next_addr = REG_ADDR + (1 << REG_SIZE);

    always @(posedge HCLK or negedge HRESETn) begin
        if(!HRESETn) begin 
            HADDR <= {ADDR_WIDTH{1'b0}};
            HBURST <= 3'd0;
            HMASTLOCK <= 1'b0;
            HPROT <= 4'b0011;
            HSIZE <= 3'd2;
            HTRANS <= IDLE;
            HWDATA <= {DATA_WIDTH{1'b0}};
            HWRITE <= 1'b0; 
            
            cs <= S_IDLE;
            BEAT_COUNT <= 8'd0;
            REG_ADDR <= {ADDR_WIDTH{1'b0}};
            REG_DATA <= {DATA_WIDTH{1'b0}};
            REG_WRITE <= 1'b0;
            REG_SIZE <= 3'd2;
            WRAP_MASK  <= {ADDR_WIDTH{1'b0}};
            
            PREADY <= 1'b1;
            RES_VALID <= 1'b0;
            RES_DATA <= {DATA_WIDTH{1'b0}}; 
            RES_ERROR <= 1'b0;
        end else begin 
            cs <= ns;
            
            case (cs)
                S_IDLE : begin
                    HTRANS    <= IDLE;
                    RES_VALID <= 1'b0;
                    
                    if(PREADY && PVALID) begin
                        REG_ADDR <= PADDR;
                        REG_DATA <= PDATA;
                        REG_WRITE <= PWRITE;
                        REG_SIZE <= PSIZE;
                        BEAT_COUNT <= (BRUST_LEN == 0) ? 8'd1 : BRUST_LEN;
                        
                        HADDR <= PADDR;
                        HSIZE <= PSIZE;
                        HWRITE <= PWRITE;
                        HPROT <= 4'b0011;
                        HMASTLOCK <= 1'b0;
                        HTRANS <= NONSEQ;
                        PREADY <= 1'b0; 
                        
                        if (BRUST_LEN == 1) begin
                            HBURST <= 3'b000; 
                            WRAP_MASK <= 0;      
                        end else if (WRAP_INCR) begin 
                            if      (BRUST_LEN == 4)  HBURST <= 3'b010; 
                            else if (BRUST_LEN == 8)  HBURST <= 3'b100; 
                            else if (BRUST_LEN == 16) HBURST <= 3'b110; 
                            else                      HBURST <= 3'b010; 
                            
                            WRAP_MASK <= ((1 << PSIZE) * BRUST_LEN) - 1;
                        end else begin
                            if      (BRUST_LEN == 4)  HBURST <= 3'b011; 
                            else if (BRUST_LEN == 8)  HBURST <= 3'b101; 
                            else if (BRUST_LEN == 16) HBURST <= 3'b111; 
                            else                      HBURST <= 3'b001; 
                            
                            WRAP_MASK <= 0;
                        end
                    end else begin 
                        PREADY <= 1'b1; 
                    end
                end

                S_ADDR: begin
                    if (HREADYOUT) begin
                        if (REG_WRITE) begin
                            HWDATA <= REG_DATA; 
                        end
                    end
                end

                S_DATA : begin 
                    if(HREADYOUT) begin 
                        if (REG_WRITE) begin
                            if(BEAT_COUNT > 1) begin 
                                BEAT_COUNT <= BEAT_COUNT - 1;
                                HTRANS <= SEQ;
                                HWDATA <= REG_DATA; 
                                
                                if(WRAP_MASK != 0) begin 
                                    REG_ADDR <= (REG_ADDR & ~WRAP_MASK) | (next_addr & WRAP_MASK);
                                    HADDR <= (REG_ADDR & ~WRAP_MASK) | (next_addr & WRAP_MASK);
                                end else begin
                                    REG_ADDR <= next_addr;
                                    HADDR <= next_addr;
                                end
                            end else begin
                                HTRANS     <= IDLE;
                                PREADY     <= 1'b1;
                                RES_VALID  <= 1'b1;
                                RES_ERROR  <= HRESP;
                            end
                        end else begin
                            RES_DATA <= HRDATA; 
                            
                            if(BEAT_COUNT > 1) begin 
                                BEAT_COUNT <= BEAT_COUNT - 1;
                                HTRANS <= SEQ;
                                
                                if(WRAP_MASK != 0) begin 
                                    REG_ADDR <= (REG_ADDR & ~WRAP_MASK) | (next_addr & WRAP_MASK);
                                    HADDR <= (REG_ADDR & ~WRAP_MASK) | (next_addr & WRAP_MASK);
                                end else begin
                                    REG_ADDR <= next_addr;
                                    HADDR <= next_addr;
                                end
                            end else begin
                                HTRANS <= IDLE;
                                PREADY <= 1'b1;
                                RES_VALID <= 1'b1;
                                RES_ERROR <= HRESP;
                            end
                            end
                end
                end
                
                default: ; 
            endcase
        
            if (RES_VALID && !PVALID) begin
                RES_VALID <= 1'b0;
            end
            end
            end

    always @(*) begin
        ns = cs; 
        
        case (cs)
            S_IDLE: begin
                if (PVALID && PREADY)
                    ns = S_ADDR;
            end
            
            S_ADDR: begin
                if (HREADYOUT)
                    ns = S_DATA;
            end
            
            S_DATA: begin
                if (HREADYOUT && (BEAT_COUNT == 1 || BEAT_COUNT == 0))
                    ns = S_IDLE;
            end
            
            default: ns = S_IDLE;
        endcase
    end

endmodule






// --- : CRITICAL AHB MASTER FIXES ---
//
// 1. BURST DATA STARVATION (In S_DATA, write burst):
//    - PREADY is currently low during the entire write burst.
//    - Must pulse PREADY high for 1 cycle when HREADYOUT==1 to fetch next PDATA.
//    - HWDATA needs to be updated with the newly fetched PDATA.
//
// 2. PIPELINE ALIGNMENT BUG (S_ADDR state):
//    - S_ADDR state breaks AHB pipelining by holding NONSEQ for 2 cycles.
//    - Remove S_ADDR. Transition directly S_IDLE -> S_ACTIVE.
//    - Drive HTRANS/HADDR for Beat(N+1) simultaneously while capturing data for Beat(N).
//
// 3. TWO-CYCLE ERROR RESPONSE (HRESP):
//    - HRESP is a 2-cycle protocol (Cycle 1: HRESP=1, HREADYOUT=0. Cycle 2: HRESP=1, HREADYOUT=1).
//    - If HRESP==1 & HREADYOUT==0 detected, MUST abort burst and force HTRANS to IDLE next cycle.
//
// 4. 1KB BOUNDARY CROSING (HADDR):
//    - AHB bursts cannot cross a 1KB (0x400) address boundary.
//    - Ensure processor never requests this, OR add hardware check to split burst into NONSEQ.
//
// 5. BYTE LANE ALIGNMENT (Optional check):
//    - Verify RISC-V core shifts PDATA to correct byte lanes based on PSIZE (e.g., HWDATA[15:8] for 8-bit write to 0x01).
//    - If core doesn't, add alignment mux here.
//
// 6. LOCKED TRANSFERS (Optional - for RV32A):
//    - HMASTLOCK is tied to 0. Not needed unless atomic instructions (LR/SC, AMO) are supported.
//    - If needed, add PLOCK input and assert HMASTLOCK during Address Phase of locked sequence.
